Stop if PRIVATE_ENV_ACCESS DNE

diff --git a/script/setup/private_environment b/script/setup/private_environment
--- a/script/setup/private_environment
+++ b/script/setup/private_environment
@@ -1,5 +1,11 @@
 #!/bin/bash
 
+if [ -z $PRIVATE_ENV_ACCESS ]
+then
+    echo "Cannot add $1.env because PRIVATE_ENV_ACCESS is not set"
+    exit 1
+fi
+
 SOURCE_DIR="$(dirname "$(realpath "$0")")"
 
 mkdir -p $SOURCE_DIR/private_environments
