add error information

diff --git a/script/setup/private_environment b/script/setup/private_environment
--- a/script/setup/private_environment
+++ b/script/setup/private_environment
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 if [ -z "$1" ]; then
-  >&2 echo "Usage: $0 <environment>"
+  >&2 echo "$(date +%D) $(date +%T) ERROR dev.env.setup.private_environment Usage: $0 <environment>"
   exit 1
 fi
 
@@ -9,7 +9,7 @@ ENV_ACCESS_TOKEN_NAME="ENV_${1^^}_ACCESS_TOKEN"
 
 if [ -z "${!ENV_ACCESS_TOKEN_NAME}" ]
 then
-  >&2 echo "Cannot add $1.env because $ENV_ACCESS_TOKEN_NAME is not set"
+  >&2 echo "$(date +%D) $(date +%T) NOTICE dev.env.setup.private_environment Cannot add $1.env because $ENV_ACCESS_TOKEN_NAME is not set"
   exit 1
 fi
 
