Add error logging support

diff --git a/script/setup/private_environment b/script/setup/private_environment
--- a/script/setup/private_environment
+++ b/script/setup/private_environment
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 if [ -z "$1" ]; then
-  echo "Usage: $0 <environment>"
+  >&2 echo "Usage: $0 <environment>"
   exit 1
 fi
 
@@ -9,8 +9,8 @@ ENV_ACCESS_TOKEN_NAME="ENV_${1^^}_ACCESS_TOKEN"
 
 if [ -z "${!ENV_ACCESS_TOKEN_NAME}" ]
 then
-    echo "Cannot add $1.env because $ENV_ACCESS_TOKEN_NAME is not set"
-    exit 1
+  >&2 echo "Cannot add $1.env because $ENV_ACCESS_TOKEN_NAME is not set"
+  exit 1
 fi
 
 SOURCE_DIR="$(dirname "$(realpath "$0")")"
